### ISSUE TITLE
Edit Assessment: Partner and lead organization selection

### ISSUE THREAD

**Issue by patricechataigner** [the-deep/deeper#106] opened 2019-01-17 10:26 UTC
Hello, the list of orgnizations is pretty long and i dont find very convenient to select all participating organizations just by scrolling down. the simpler would be to be able to type the name of the partner and then to see the naem appearing in the menu below. in practice this work for the first name we type but not for the second tthird and next ones. Is there any more convenient solution? separating names by semi coma for instance? if there is a better solution please let me know.

**Comment by eoglethorpe** [comment] 2019-02-20 16:20
we can close this right? it's a duplicate of #183

**Comment by tnagorra** [comment] 2019-03-08 09:36
Duplicate of https://github.com/the-deep/deeper/issues/183

**Closed** 2019-04-04 15:32 UTC
Labels: discussion, duplicate, related-client
