### ISSUE TITLE
Tabular: Edit entries: Visualizations reset when out of visual scope

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#292] opened 2019-03-21 08:47 UTC
1) change column chart type on left panel
2) scroll so that the column is out view
3) scroll back to column, it's reset

**Comment by AdityaKhatri** [comment] 2019-04-04 07:06
This is the expected behavior.
Due to virtualization, everything that is out of scope is dismounted. If we need to do what you suggest, we've to save the state.
This will take time and we need to research on this more.

**Comment by eoglethorpe** [comment] 2019-04-04 11:44
i would say this is a bug and should be fixed - i don't think a user would expect the graphs to reset just because they go out of view

**Closed** 2019-04-07 06:11 UTC
