### ISSUE TITLE
entries tagging: nlp: no suggestions for categorization

### ISSUE THREAD

**Issue by eoglethorpe** [the-deep/deeper#228] opened 2019-02-28 13:43 UTC
https://beta.thedeep.io/projects/397/leads/432/edit-entries/#/overview

@bewakes

**Comment by bewakes** [comment] 2019-02-28 14:57
I cannot access that page @eoglethorpe , but I will look into the issue.

**Comment by eoglethorpe** [comment] 2019-02-28 15:37
you can just add yourself to the project?

**Comment by eoglethorpe** [comment] 2019-04-03 11:56
@bewakes @amarshahi ?

**Comment by bewakes** [comment] 2019-04-04 10:39
@eoglethorpe, the issue is that, sometimes, requests sent to DEEPL by DEEP server fail so DEEP won't get the classified_doc_id. I'll write a script to re-send requests to DEEPL and this will be fixed.

**Closed** 2020-10-29 10:22 UTC
Labels: bug, related-deepl
