### ISSUE TITLE
Connector: ACAPS Connector not working properly

### ISSUE THREAD

**Issue by frozenhelium** [the-deep/deeper#862] opened 2019-10-17 04:56 UTC
![connector](https://user-images.githubusercontent.com/4931541/66978682-a1cae700-f0ca-11e9-91c6-fbebf170a0dd.png)

**Comment by AdityaKhatri** [comment] 2019-10-20 06:48
Duplicate of https://github.com/the-deep/deeper/issues/703

**Closed by AdityaKhatri** 2019-10-20 06:48 UTC
Labels: prio-mid, related-client
